In [1]:
import numpy as np

In [4]:
one=np.ones((5,6))
one.shape

(5, 6)

In [5]:
arr=np.arange(8)

In [6]:

arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [9]:
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
arr.ravel('F')

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
arr11=np.array([[1,2,3,4],[5,6,7,8]])
arr22=np.array([[11,22,33,44],[55,66,77,88]])


In [20]:
k=np.concatenate([arr11,arr22],axis=0)
k

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44],
       [55, 66, 77, 88]])

In [21]:
k=np.concatenate([arr11,arr22],axis=1)
k

array([[ 1,  2,  3,  4, 11, 22, 33, 44],
       [ 5,  6,  7,  8, 55, 66, 77, 88]])

In [22]:
np.vstack((arr11,arr22))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44],
       [55, 66, 77, 88]])

In [23]:
np.hstack((arr11,arr22))

array([[ 1,  2,  3,  4, 11, 22, 33, 44],
       [ 5,  6,  7,  8, 55, 66, 77, 88]])

In [25]:
x=np.random.randn(5,2)
x

array([[ 0.02863057, -1.37826521],
       [ 1.71276424, -0.68078353],
       [ 0.12195776,  1.64897792],
       [ 0.08730555, -0.30382001],
       [-0.85238743, -0.32456668]])

In [26]:
first,second,third=np.split(x,[1,3])

In [27]:
first

array([[ 0.02863057, -1.37826521]])

In [28]:
second

array([[ 1.71276424, -0.68078353],
       [ 0.12195776,  1.64897792]])

In [29]:
third

array([[ 0.08730555, -0.30382001],
       [-0.85238743, -0.32456668]])