In [1]:
import  numpy as np

In [2]:
loop=np.arange(100)
print(loop)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [3]:
df=np.random.randn(2,3)
df

array([[-0.46654755, -0.40948232, -1.44226491],
       [-0.42195203,  0.05077103,  0.01646042]])

In [4]:
df*12

array([[ -5.59857064,  -4.91378787, -17.30717889],
       [ -5.06342436,   0.6092524 ,   0.19752507]])

In [5]:
df+df

array([[-0.93309511, -0.81896464, -2.88452981],
       [-0.84390406,  0.10154207,  0.03292084]])

In [6]:
df-df

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
df.shape

(2, 3)

In [8]:
df.dtype

dtype('float64')

In [10]:
data=[1,2,3,4,5]
array=np.array(data)
array

array([1, 2, 3, 4, 5])