In [1]:
import numpy as np


In [2]:
arr=np.random.randn(5,6)
arr

array([[-0.58415628,  1.20542005, -0.30264321, -0.82895398, -0.81364441,
         1.15952336],
       [ 0.23924157,  0.2744488 ,  0.53731035,  0.20742056, -0.2426017 ,
         0.71755765],
       [-0.05278791,  0.26483425, -1.72605259,  1.26674092, -0.96364581,
        -0.70849673],
       [ 1.20765739, -1.00884526, -1.21428499,  0.68116423, -0.9874259 ,
         1.69206921],
       [ 1.12116048,  0.05573635, -0.66657665, -0.16609526,  1.55916131,
        -0.52138532]])

In [4]:
arr.max()

1.6920692140986386

In [5]:
arr.min()

-1.7260525877881383

In [6]:
arr.mean()

0.0467283492580787

In [7]:
arr.std()

0.9005016173555619

In [8]:
arr.var()

0.8109031628599828

In [10]:
arr.sort()
arr

array([[-0.82895398, -0.81364441, -0.58415628, -0.30264321,  1.15952336,
         1.20542005],
       [-0.2426017 ,  0.20742056,  0.23924157,  0.2744488 ,  0.53731035,
         0.71755765],
       [-1.72605259, -0.96364581, -0.70849673, -0.05278791,  0.26483425,
         1.26674092],
       [-1.21428499, -1.00884526, -0.9874259 ,  0.68116423,  1.20765739,
         1.69206921],
       [-0.66657665, -0.52138532, -0.16609526,  0.05573635,  1.12116048,
         1.55916131]])

In [22]:
x=np.array([[1,2,3],[8,9,10]])
y=np.array([[11,22],[44,55],[99,00,]])

In [23]:
x

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [24]:
y

array([[11, 22],
       [44, 55],
       [99,  0]])

In [25]:
np.dot(x,y)

array([[ 396,  132],
       [1474,  671]])

In [26]:
y.dot(x)

array([[187, 220, 253],
       [484, 583, 682],
       [ 99, 198, 297]])

In [28]:
y.dot(np.ones(2))

array([33., 99., 99.])

In [48]:
from numpy.linalg import inv,qr,det,eig

In [34]:
x= np.random.randn(4,3)
x

array([[ 0.81604759,  0.1442816 , -0.79095859],
       [-1.66956957,  0.16335624,  0.37113088],
       [ 0.41437658,  0.52645523, -0.2150472 ],
       [-0.52760685, -0.11369219, -1.24895966]])

In [38]:
matrix=x.T.dot(x)
matrix

array([[ 3.90347315,  0.12314153, -0.69523952],
       [ 0.12314153,  0.33758346, -0.02470999],
       [-0.69523952, -0.02470999,  2.36949916]])

In [39]:
inv(matrix)

array([[ 0.27324898, -0.09387716,  0.07919555],
       [-0.09387716,  2.99674563,  0.00370645],
       [ 0.07919555,  0.00370645,  0.44530569]])

In [40]:
matrix.dot(inv(matrix))

array([[ 1.00000000e+00, -4.64038530e-17,  5.55111512e-17],
       [ 6.50521303e-18,  1.00000000e+00,  1.73472348e-18],
       [-2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

In [41]:
q,r=qr(matrix)
r

array([[-3.96681541, -0.13598555,  1.10019263],
       [ 0.        , -0.33353402,  0.0086784 ],
       [ 0.        ,  0.        ,  2.21088121]])

In [44]:
det(matrix)

2.925145963270891

In [49]:
eig(matrix)

(array([4.17567271, 2.1015473 , 0.33333577]),
 array([[ 9.32616118e-01,  3.59226981e-01, -3.43969693e-02],
        [ 3.22361506e-02,  1.20053861e-02,  9.99408176e-01],
        [-3.59427331e-01,  9.33172999e-01,  3.83678497e-04]]))